version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  greeting2:
    docker:
      - image: debian:buster

    steps:
      - run:
          name: Greeting2
          command: echo "Hi!!"
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  greeting1:
    jobs:
      - build
  greeting2:
    jobs:
      - greeting2
