version: 2
jobs:
  checkout:
    docker:
      - image: debian:buster
    working_directory: ~/demo
    steps:
      - checkout
      - save_cache:
          key: demo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/demo


  greeting: &greeting
    docker:
      - image: debian:buster

    steps:
      - restore_cache:
          keys:
            - demo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: sleep 20 && date
  greeting1:
    <<: *greeting
  greeting2:
    <<: *greeting
  greeting3:
    <<: *greeting
  greeting4:
    <<: *greeting
  greeting5:
    <<: *greeting
  greeting6:
    <<: *greeting
  greeting7:
    <<: *greeting
  greeting8:
    <<: *greeting


  bye:
    docker:
      - image: debian:buster

    steps:
      - restore_cache:
          keys:
            - demo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: bye
          command: echo bye bye

workflows:
  version: 2
  flow:
    jobs:
      - checkout
      - greeting1:
          requires:
            - checkout
      
      - greeting2:
          requires:
            - checkout
      - greeting3:
          requires:
            - checkout
      - greeting4:
          requires:
            - checkout
      - greeting5:
          requires:
            - checkout
      - greeting6:
          requires:
            - checkout
      - greeting7:
          requires:
            - checkout
      - greeting8:
          requires:
            - checkout
      - bye:
          requires:
            - greeting1
            - greeting2
            - greeting3
            - greeting4
            - greeting5
            - greeting6
            - greeting7
            - greeting8

