version: 2
jobs:
  checkout:
    docker:
      - image: debian:buster
    working_directory: ~/demo
    steps:
      - checkout
      - save_cache:
          key: demo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/demo


  greeting1:
    docker:
      - image: debian:buster

    steps:
      - restore_cache:
          keys:
            - demo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: sleep 20 && date
  greeting2:
    docker:
      - image: debian:buster

    steps:
      - restore_cache:
          keys:
            - demo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Greeting2
          command: echo "Hi!!"
      - run:
          name: Print the Current Time
          command: sleep 20 && date

  bye:
    docker:
      - image: debian:buster

    steps:
      - restore_cache:
          keys:
            - demo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: bye
          command: echo bye bye

workflows:
  version: 2
  greeting1:
    jobs:
      - checkout
      - greeting1:
          requires:
            - checkout
      
      - greeting2:
          requires:
            - checkout
      - bye:
          requires:
            - greeting1
            - greeting2
